### ISSUE TITLE
Bower package?

### ISSUE THREAD

**Issue by niksy** [HugoGiraudel/SassyJSON#80]
Are you will to publish SassyJSON as Bower package (or accept PR for that)?

**Comment by esr360** [comment]
Hope you don't mind me putting my two-cents here - not sure why you are so strongly against people using this in production - I've been using it on a local project I've been developing this past month, and it's been a godsend so far. I see much more "experimental" stuff that people use in production than this.

So I if it means anything at all, I +1 this issue :)

**Comment by HugoGiraudel** [comment]
I do not want people to use it in production because:

* It is an experiment. The point was to see if it is possible to write a parser in Sass. Here a JSON one. It turns out it is.
* I did not manage to implement the full JSON spec. Some bites are missing such as escaped characters which I cannot handle with Sass because Sass is terrible with escaped sequences.
* There has been some regression because Sass decided to change the way it handled line breaks. While it was working before, it does not anymore and not being able to deal with line breaks is kind of a big deal.
* It is extremely slow. Of course it is incredibly slow. Sass is slow by design, even with LibSass (although it is definitely better than Ruby Sass). It is not meant to parse JSON.
* The correct way of reading and writing JSON data from Sass is to have a build step or a correct plugin. Both LibSass and Ruby Sass allow custom functions. It should be a breeze to implement a JSON API to the Sass layer.

**Comment by niksy** [comment]
I think @HugoGiraudel made pretty good explanation for this so I think this can be closed :)
